### ISSUE TITLE
Will it work with the 2nd generation Yeelight?

### ISSUE THREAD

**Issue by soloam** [Gromina/node-red-contrib-yeelight#7]
Hello will this work with the 2nd generation? https://www.gearbest.com/smart-lighting/pp_1664464.html?wid=1640583

Thank you

**Comment by Gromina** [comment]
probably yes, but I stopped supporting this repo in favor to https://github.com/Gromina/node-red-contrib-miio-wrapper (more generic solution).

**Comment by scargill** [comment]
I see the Yeelight node has had more reecent updating - you looked in there recently? This could now bw a  useful node with fewer manufacturers putting ESP8266 in thei lights etc... But it needs to respond to name of MAC  - anything other than IP. Also I cann;t fathom how to use several asttings with one node - i.e.l on-off, colour etc, it LOOKS like you need separate nodes for each control - any feedback would be appreciated.

**Comment by Gromina** [comment]
As I said earlier, I stopped supporting this repo. I personally switched to Home assistant, so no need to support this one.
But you're welcome to make pull requests adding new features. PTS93 contributes a lot to the repo, so probably you can talk to him.

**Comment by PTS93** [comment]
I mostly did some fixes to reduce crashes related to lights not being available on the network all the time.
I still use it actively but not much time on hand to introduce new features, sorry.
Regarding your question of using multiple light and the config node in general; Config nodes are not nodes placed on the screen but are "hidden". You create config nodes via the drop down menu and choose "create new config" and then click on edit. You can create a config for each of your lights.
![image](https://user-images.githubusercontent.com/2370185/102091777-90d94b00-3e1f-11eb-9611-b2b0ecefab57.png)

Not sure why you want to identify lights by their mac address instead of their IP but that is not really trivial to implement.

**Comment by scargill** [comment]
I understand that the config is built into the node... no problem there - I might be missing something - but my first node configures the Yeelight - no problem - and turns it on and off - but it seems that i have to use ANOTHER of these nodes to change colour as I put set power as the command in the first node... is there a way to INJECT the command so you only have to use the one node??

**Comment by timonsku** [comment]
ah no, thats not a feature atm. If you want a different command you would have to add a second node but that can of course re-use the same config
